# Generated by Django 4.2.2 on 2023-07-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Information_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Information_password', models.CharField(blank=True, max_length=150, null=True)),
                ('Information_phone', models.IntegerField(unique=True)),
                ('Information_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Information_used', models.BooleanField(default=False, null=True)),
                ('Information_spam', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
