# Generated by Django 4.2.2 on 2023-07-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='Information_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=50, null=True),
        ),
    ]
