# Generated by Django 4.2.2 on 2023-07-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamapp', '0002_alter_information_information_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='Information_spam',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
